function log_pZ = compute_pZ(data,samples,hyper,param)

idxAct = find(sum(samples.seq~=0,2)>0);
Mplus = length(idxAct);

log_pZ = Mplus*log(hyper.alpha)-hyper.alpha*harmonic(param.T);
for ii=1:length(idxAct)
    m = idxAct(ii);
    
    log_pZ = log_pZ ...
             +gammaln(samples.nest(1,2,m))+gammaln(samples.nest(1,1,m)+1) ...
             +gammaln(hyper.gamma1+hyper.gamma2) ...
             +gammaln(hyper.gamma1+samples.nest(2,1,m))+gammaln(hyper.gamma2+samples.nest(2,2,m)) ...
             -gammaln(samples.nest(1,1,m)+samples.nest(1,2,m)+1) ...
             -gammaln(hyper.gamma1)-gammaln(hyper.gamma2) ...
             -gammaln(samples.nest(2,1,m)+samples.nest(2,2,m)+hyper.gamma1+hyper.gamma2);
end
